version: 0.0
os: linux

files:
  - source: /builds    # This reflects the extracted contents from builds/build.zip
    destination: /var/www/oriserve_react # Destination directory on the instance (you can modify this)

permissions:
  - object: /var/www/oriserve_react
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
      - directory
    recurse: true

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh  # Script to install dependencies
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/change_permissions.sh    # Script to change permissions
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh          # Script to start the server
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh      # Script for validation (health check)
      timeout: 300
      runas: root
